---
- name: Harden Windows Security Protocols
  hosts: windows
  gather_facts: yes
  any_errors_fatal: false
  
  vars:
    reboot_required: false
    security_changes_made: false
    
    # Протоколы для отключения
    disable_protocols:
      - SMB1
      - SMB2  # В некоторых случаях, если нужен только SMB3
      - TLS1.0
      - TLS1.1
      - SSL2.0
      - SSL3.0
      - RC4
      - DES
      - 3DES
      - NULL
      - EXPORT
    
    # Службы для отключения
    disable_services:
      - Telnet
      - FTP
      - SNMP
      - LLMNR
      - NetBIOS

  tasks:
  - name: Gather Windows facts
    setup:
      gather_subset:
        - min
    
  - name: Проверка версии Windows
    win_shell: |
      [System.Environment]::OSVersion.Version
    register: os_version
    changed_when: false
    
  - name: Отключение SMBv1 (если включен)
    block:
    - name: Проверка состояния SMBv1
      win_shell: |
        Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol
      register: smb1_status
      changed_when: false
      
    - name: Отключение SMBv1
      win_shell: |
        Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart
      when: "'Enabled' in smb1_status.stdout"
      register: disable_smb1
      ignore_errors: yes
      
    - name: Отметка необходимости перезагрузки для SMBv1
      set_fact:
        reboot_required: true
        security_changes_made: true
      when: disable_smb1 is succeeded
    
  - name: Настройка протоколов SMB
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      type: "{{ item.type }}"
      state: present
    with_items:
      - { name: SMB1, data: 0, type: dword }
      - { name: SMB2, data: 1, type: dword }
    register: smb_registry
    when: "'SMB1' in disable_protocols or 'SMB2' in disable_protocols"
    
  - name: Отключение устаревших TLS/SSL протоколов через реестр
    win_regedit:
      path: "{{ item.path }}"
      name: Enabled
      data: 0
      type: dword
      state: present
    with_items:
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client }
    register: tls_registry
    when: "'TLS1.0' in disable_protocols or 'TLS1.1' in disable_protocols or 'SSL2.0' in disable_protocols or 'SSL3.0' in disable_protocols"
    
  - name: Включение TLS 1.2 и 1.3
    win_regedit:
      path: "{{ item.path }}"
      name: Enabled
      data: 1
      type: dword
      state: present
    with_items:
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server }
      - { path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client }
    register: tls_enable
    
  - name: Отключение слабых шифров
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers
      name: "{{ item }}"
      state: absent
    with_items:
      - "DES 56/56"
      - "NULL"
      - "RC2 128/128"
      - "RC2 40/128"
      - "RC2 56/128"
      - "RC4 128/128"
      - "RC4 40/128"
      - "RC4 56/128"
      - "RC4 64/128"
      - "Triple DES 168"
    when: "'RC4' in disable_protocols or 'DES' in disable_protocols or '3DES' in disable_protocols"
    register: cipher_changes
    
  - name: Отключение службы Telnet
    win_service:
      name: TlntSvr
      state: stopped
      start_mode: disabled
    register: telnet_service
    when: "'Telnet' in disable_services"
    
  - name: Отключение NetBIOS через TCP/IP
    win_regedit:
      path: "HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces"
      name: NetbiosOptions
      data: 2
      type: dword
      state: present
    when: "'NetBIOS' in disable_services"
    register: netbios_changes
    
  - name: Отключение LLMNR
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient
      name: EnableMulticast
      data: 0
      type: dword
      state: present
    when: "'LLMNR' in disable_services"
    register: llmnr_changes
    
  - name: Отключение устаревших методов аутентификации
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
      name: "{{ item.name }}"
      data: "{{ item.value }}"
      type: dword
      state: present
    with_items:
      - { name: LMCompatibilityLevel, value: 5 }
      - { name: RestrictSendingNTLMTraffic, value: 1 }
      - { name: NTLMMinClientSec, value: 537395200 }
      - { name: NTLMMinServerSec, value: 537395200 }
    register: auth_changes
    
  - name: Настройка безопасных сетевых параметров
    win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
      name: DisabledComponents
      data: 255
      type: dword
      state: present
    register: ipv6_changes
    
  - name: Применение настроек брандмауэра
    win_shell: |
      # Блокировка входящих подключений по устаревшим протоколам
      New-NetFirewallRule -DisplayName "Block SMBv1" -Direction Inbound -Protocol TCP -LocalPort 445 -Action Block -Enabled True
      New-NetFirewallRule -DisplayName "Block Telnet" -Direction Inbound -Protocol TCP -LocalPort 23 -Action Block -Enabled True
      New-NetFirewallRule -DisplayName "Block FTP" -Direction Inbound -Protocol TCP -LocalPort 21 -Action Block -Enabled True
    when: security_changes_made
    register: firewall_rules
    
  - name: Проверка необходимости перезагрузки
    win_shell: |
      $reboot = $false
      if ((Get-WmiObject -Class Win32_OperatingSystem).LastBootUpTime -lt (Get-Date).AddMinutes(-1)) {
        # Проверяем ожидающие перезагрузки операции
        $pending = (Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager" -Name PendingFileRenameOperations -ErrorAction SilentlyContinue)
        if ($pending) { $reboot = $true }
        
        # Проверка других признаков необходимости перезагрузки
        $cbs = (Get-ChildItem "HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending" -ErrorAction SilentlyContinue)
        if ($cbs) { $reboot = $true }
      }
      Write-Output $reboot
    register: reboot_check
    changed_when: false
    
  - name: Перезагрузка при необходимости
    win_reboot:
      msg: "Перезагрузка для применения изменений безопасности"
      reboot_timeout: 600
      pre_reboot_delay: 60
      post_reboot_delay: 120
      test_command: whoami
    when: reboot_required or reboot_check.stdout == "True"
    
  - name: Проверка примененных настроек
    win_shell: |
      Write-Output "=== Проверка безопасности ==="
      Write-Output "SMBv1 статус:"
      Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol | Select-Object State
      Write-Output "`nTLS протоколы:"
      Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\*\*" -Name Enabled -ErrorAction SilentlyContinue | Format-Table -AutoSize
      Write-Output "`nСлужбы:"
      Get-Service -Name TlntSvr -ErrorAction SilentlyContinue | Select-Object Name, Status, StartType
    register: security_check
    changed_when: false
    
  - name: Создание отчета о выполнении
    copy:
      content: |
        Отчет о выполнении харденинга безопасности Windows
        =================================================
        Хост: {{ inventory_hostname }}
        Время: {{ ansible_date_time.iso8601 }}
        
        Выполненные изменения:
        - Отключен SMBv1: {{ 'Да' if disable_smb1 is defined and disable_smb1 is succeeded else 'Нет' }}
        - Настроены TLS протоколы: {{ 'Да' if tls_registry is defined and tls_registry.changed else 'Нет' }}
        - Отключены слабые шифры: {{ 'Да' if cipher_changes is defined and cipher_changes.changed else 'Нет' }}
        - Отключен Telnet: {{ 'Да' if telnet_service is defined and telnet_service.changed else 'Нет' }}
        - Настроена аутентификация: {{ 'Да' if auth_changes is defined and auth_changes.changed else 'Нет' }}
        
        Перезагрузка выполнена: {{ 'Да' if reboot_required else 'Нет' }}
        
        Результаты проверки:
        {{ security_check.stdout }}
        
      dest: "C:\Security_Hardening_Report_{{ inventory_hostname }}.txt"
    when: security_changes_made
    delegate_to: localhost
    
  - name: Вывод сводки
    debug:
      msg: |
        Харденинг безопасности Windows выполнен на {{ inventory_hostname }}
        Изменения применены: {{ 'Да' if security_changes_made else 'Нет' }}
        Требовалась перезагрузка: {{ 'Да' if reboot_required else 'Нет' }}
        
        Для просмотра подробного отчета проверьте файл:
        C:\Security_Hardening_Report_{{ inventory_hostname }}.txt
