---
- name: Сбор информации о системе Windows 7
  hosts: windows7_hosts  # Укажите группу хостов Windows 7 в вашем inventory
  gather_facts: no  # Отключаем сбор фактов Ansible (может не работать на Windows 7)

  tasks:
    - name: Получить информацию о системе через PowerShell
      ansible.windows.win_powershell:
        script: |
          $info = @{
            ComputerName = $env:COMPUTERNAME
            OSVersion = (Get-WmiObject Win32_OperatingSystem).Caption
            OSArchitecture = (Get-WmiObject Win32_OperatingSystem).OSArchitecture
            TotalMemoryGB = [math]::Round((Get-WmiObject Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
            CPU = (Get-WmiObject Win32_Processor).Name
            DiskSizeGB = Get-WmiObject Win32_LogicalDisk | Where-Object {$_.DriveType -eq 3} | ForEach-Object {[math]::Round($_.Size / 1GB, 2)}
            LastBootTime = (Get-WmiObject Win32_OperatingSystem).LastBootUpTime
          }
          ConvertTo-Json -InputObject $info -Compress
      register: system_info

    - name: Вывод информации о системе
      debug:
        msg: "{{ system_info.output | from_json }}"
